export const VERIFICATION_STEP = {
  LIVENESS_CHECKING: "LIVENESS_CHECKING",
  LIVENESS_COMPLETE: "LIVENESS_COMPLETE",
  LIVENESS_FAILED: "LIVENESS_FAILED",
  REGISTRATION_STARTED: "REGISTRATION_STARTED",
  REGISTRATION_COMPLETE: "REGISTRATION_COMPLETE",
  REGISTRATION_FAILED: "REGISTRATION_FAILED",
};

export const VERIFICATION_STEP_LABELS = {
  [VERIFICATION_STEP.LIVENESS_CHECKING]: "Checking face liveness…",
  [VERIFICATION_STEP.LIVENESS_COMPLETE]: "Face liveness complete",
  [VERIFICATION_STEP.LIVENESS_FAILED]: "Face liveness failed",
  [VERIFICATION_STEP.REGISTRATION_STARTED]: "Face registration started…",
  [VERIFICATION_STEP.REGISTRATION_COMPLETE]: "Face registration complete — redirecting…",
  [VERIFICATION_STEP.REGISTRATION_FAILED]: "Face registration failed",
};

export const FAILED_VERIFICATION_STEPS = new Set([
  VERIFICATION_STEP.LIVENESS_FAILED,
  VERIFICATION_STEP.REGISTRATION_FAILED,
]);

export const COMPLETE_VERIFICATION_STEPS = new Set([
  VERIFICATION_STEP.LIVENESS_COMPLETE,
  VERIFICATION_STEP.REGISTRATION_COMPLETE,
]);