export const VERIFICATION_STEP = {
  LIVENESS_CHECKING: "LIVENESS_CHECKING",
  LIVENESS_COMPLETE: "LIVENESS_COMPLETE",
  LIVENESS_FAILED: "LIVENESS_FAILED",

  VERIFY_STARTED: "VERIFY_STARTED",
  VERIFY_COMPLETE: "VERIFY_COMPLETE",
  VERIFY_FAILED: "VERIFY_FAILED",

  REGISTRATION_STARTED: "REGISTRATION_STARTED",
  REGISTRATION_COMPLETE: "REGISTRATION_COMPLETE",
  REGISTRATION_FAILED: "REGISTRATION_FAILED",

  MULTIPLE_FACES_DETECTED: "MULTIPLE_FACES_DETECTED",
  POOR_IMAGE_QUALITY: "POOR_IMAGE_QUALITY",
  SESSION_EXPIRED: "SESSION_EXPIRED",
  CONNECTION_ERROR: "CONNECTION_ERROR",
};

export const VERIFICATION_STEP_LABELS = {
  [VERIFICATION_STEP.LIVENESS_CHECKING]: "Checking face liveness…",
  [VERIFICATION_STEP.LIVENESS_COMPLETE]: "Face liveness complete",
  [VERIFICATION_STEP.LIVENESS_FAILED]: "Face liveness failed",

  [VERIFICATION_STEP.VERIFY_STARTED]: "Verifying your identity…",
  [VERIFICATION_STEP.VERIFY_COMPLETE]: "Identity verified — redirecting…",
  [VERIFICATION_STEP.VERIFY_FAILED]: "We couldn't verify your identity",

  [VERIFICATION_STEP.REGISTRATION_STARTED]: "Registering your face…",
  [VERIFICATION_STEP.REGISTRATION_COMPLETE]: "Face registration complete — redirecting…",
  [VERIFICATION_STEP.REGISTRATION_FAILED]: "Face registration failed",

  [VERIFICATION_STEP.MULTIPLE_FACES_DETECTED]: "Multiple faces were detected",
  [VERIFICATION_STEP.POOR_IMAGE_QUALITY]: "Image quality was too low",
  [VERIFICATION_STEP.SESSION_EXPIRED]: "Verification session expired",
  [VERIFICATION_STEP.CONNECTION_ERROR]: "Connection problem",
};

export const FAILED_VERIFICATION_STEPS = new Set([
  VERIFICATION_STEP.LIVENESS_FAILED,
  VERIFICATION_STEP.VERIFY_FAILED,
  VERIFICATION_STEP.REGISTRATION_FAILED,
  VERIFICATION_STEP.MULTIPLE_FACES_DETECTED,
  VERIFICATION_STEP.POOR_IMAGE_QUALITY,
  VERIFICATION_STEP.SESSION_EXPIRED,
  VERIFICATION_STEP.CONNECTION_ERROR,
]);

export const COMPLETE_VERIFICATION_STEPS = new Set([
  VERIFICATION_STEP.LIVENESS_COMPLETE,
  VERIFICATION_STEP.VERIFY_COMPLETE,
  VERIFICATION_STEP.REGISTRATION_COMPLETE,
]);

export const REQUIRES_NEW_SESSION_STEPS = new Set([
  VERIFICATION_STEP.LIVENESS_FAILED,
  VERIFICATION_STEP.VERIFY_FAILED,
  VERIFICATION_STEP.MULTIPLE_FACES_DETECTED,
  VERIFICATION_STEP.POOR_IMAGE_QUALITY,
  VERIFICATION_STEP.SESSION_EXPIRED,
  VERIFICATION_STEP.CONNECTION_ERROR,
]);